- hosts: builder
  become: true
  collections:
    - deevnet.builder
  roles:
    - base

- hosts: workstations
  become: true
  collections:
    - deevnet.builder
  roles:
    - workstation

- hosts: artifact_servers
  become: true
  collections:
    - deevnet.builder
  roles:
    - artifacts
