---
- name: Ensure Ansible is installed
  package:
    name: ansible
    state: present


- name: Remove legacy /opt/dvnt workspace
  ansible.builtin.file:
    path: /opt/dvnt
    state: absent
  become: true
