---
# General development tools
- name: Ensure dev tool packages are present
  become: true
  ansible.builtin.dnf:
    name: "{{ dev_tool_packages }}"
    state: present

- name: Ensure X11 packages are present
  become: true
  ansible.builtin.dnf:
    name: "{{ x11_packages }}"
    state: present